// Generated by CoffeeScript 1.7.1
(function() {
  var GeekBikeController,
    __indexOf = [].indexOf || function(item) { for (var i = 0, l = this.length; i < l; i++) { if (i in this && this[i] === item) return i; } return -1; };

  GeekBikeController = (function() {
    GeekBikeController.isCompatible = function() {
      return __indexOf.call(window, GeekBikeAgent) >= 0;
    };

    function GeekBikeController(ridingCallback, turningCallback) {
      this.ridingCallback = ridingCallback;
      this.turningCallback = turningCallback;
      this.active = true;
    }

    GeekBikeController.prototype.updateAvailable = function() {
      if (!this.active) {
        return false;
      }
    };

    return GeekBikeController;

  })();

}).call(this);
